name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: "Check if artifact has already been built"
        id: dwnld
        uses: actions/download-artifact@v2
        with:
          name: ${{ steps.get-commit.outputs.commit }}_${{ matrix.apps }}
      - name: The job has failed
        if: ${{ failure() }}
        run: echo fails
  build_artifact:
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
      - run: echo ${{ needs.job1.result }}
